{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8d203767-90b2-4491-ab11-de17ae28c8c9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Воскресенья в November 2025: 2; 9; 16; 23; 30\n",
      "kashey_bessmertny: kashey_bessmertny;12;4;8;-;-;12;4;8;-;-;12;4;8;-;-;12;4;8;-;B;12;4;8;-;-;12;4;8;B;-;144;48\n",
      "baba_yaga: baba_yaga;-;12;4;8;-;-;12;4;8;-;B;12;4;8;-;-;12;4;8;B;-;12;4;8;-;-;12;4;8;-;144;48\n",
      "ivan_tsarevich: ivan_tsarevich;-;B;12;4;8;-;-;12;4;8;B;-;12;4;8;-;-;12;4;8;-;-;12;4;8;-;-;12;4;8;144;48\n",
      "tsarevna_lyagushka: tsarevna_lyagushka;0;B;-;12;4;8;-;-;12;4;8;-;-;12;4;8;-;-;12;4;8;-;-;12;4;8;-;B;12;4;136;40\n",
      "Файл Excel успешно создан!\n",
      "\n",
      "Работа программы завершена\n"
     ]
    }
   ],
   "source": [
    "#создание графика работы\n",
    "import os\n",
    "from pathlib import Path\n",
    "#задаем путь к файлу\n",
    "# Или для общей папки Documents:\n",
    "base_dir = r\"C:\\Users\\user0907\\documents\"\n",
    "path_file = os.path.join(base_dir, 'people.txt')\n",
    "import sys\n",
    "import pandas as pd\n",
    "from matplotlib import pyplot as plt\n",
    "\n",
    "if sys.version_info < (3, 6):\n",
    "    print(\"Требуется Python 3.6 или выше!\")\n",
    "    sys.exit(1)\n",
    "\n",
    "from datetime import date\n",
    "#Получаем дату через 2 месяца от текущей\n",
    "today = date.today()\n",
    "year = today.year\n",
    "month = today.month\n",
    "\n",
    "# Корректируем год, если месяц +2 выходит за пределы 12\n",
    "if month + 2 > 12:\n",
    "    year += 1\n",
    "    month = (month + 2) - 12\n",
    "else:\n",
    "    month += 2\n",
    "import calendar\n",
    "days_in_month = calendar.monthrange(year, month)[1]\n",
    "#print(days_in_month)\n",
    "# Получаем матрицу календаря месяца (недели в строках)\n",
    "month_calendar = calendar.monthcalendar(year, month)\n",
    "\n",
    "# Воскресенья находятся в последнем столбце (индекс 6)\n",
    "sundays = [\n",
    "    week[6]\n",
    "    for week in month_calendar\n",
    "    if week[6] != 0  # Игнорируем нули (дни из других месяцев)\n",
    "]\n",
    "\n",
    "# Формируем надпись\n",
    "month_name = date(year, month, 1).strftime('%B')  # Получаем название месяца\n",
    "print(f\"Воскресенья в {month_name} {year}: {'; '.join(map(str, sundays))}\")\n",
    "\n",
    "\n",
    "line_work = [12,4,\"-\",\"-\"]\n",
    "body_2 = [\"-\", 12,4,\"-\"]\n",
    "body_3 = [\"-\",\"-\",12,4]\n",
    "body_4 = [4,\"-\",\"-\",12]\n",
    "def duble(list):\n",
    "    while len(list) < days_in_month:\n",
    "        list += list\n",
    "    line_work_31 = (list)[:days_in_month]\n",
    "    # Заменяем '-' на 'B' в воскресенья\n",
    "    for i in range(len(line_work_31)):\n",
    "        if (i+1) in sundays and line_work_31[i] == '-':  # i+1 потому что дни месяца начинаются с 1\n",
    "            line_work_31[i] = 'B'\n",
    "    #заменяем первую 4 в графике на 0\n",
    "    if line_work_31[0] == 4:\n",
    "        line_work_31[0] = 0\n",
    "    # Добавляем \"8\" после каждого \"4\"\n",
    "    new_list = []\n",
    "    for item in line_work_31:\n",
    "        new_list.append(item)\n",
    "        if item == 4:\n",
    "            new_list.append(8)\n",
    "            \n",
    "    # Обрезаем до нужной длины, если добавили лишние элементы\n",
    "    return new_list[:days_in_month]\n",
    "\n",
    "kashey_bessmertny = duble(line_work)\n",
    "kashey_bessmertny_sum_11 = sum(x for x in kashey_bessmertny if x == 12 or x == 4 or x == 8)\n",
    "kashey_bessmertny_sum_8 = sum(x for x in kashey_bessmertny if x == 8)\n",
    "# Добавляем сумму в конец списка\n",
    "kashey_bessmertny.insert(0, \"kashey_bessmertny\")\n",
    "kashey_bessmertny.append(kashey_bessmertny_sum_11)\n",
    "kashey_bessmertny.append(kashey_bessmertny_sum_8)\n",
    "\n",
    "baba_yaga = duble(body_2)\n",
    "baba_yaga_sum_11 = sum(x for x in baba_yaga if x == 12 or x == 4 or x == 8)\n",
    "baba_yaga_sum_8 = sum(x for x in baba_yaga if x == 8)\n",
    "# Добавляем сумму в конец списка\n",
    "baba_yaga.insert(0, \"baba_yaga\")\n",
    "baba_yaga.append(baba_yaga_sum_11)\n",
    "baba_yaga.append(baba_yaga_sum_8)\n",
    "\n",
    "\n",
    "ivan_tsarevich = duble(body_3)\n",
    "ivan_tsarevich_sum_11 = sum(x for x in ivan_tsarevich if x == 12 or x == 4 or x == 8)\n",
    "ivan_tsarevich_sum_8 = sum(x for x in ivan_tsarevich if x == 8)\n",
    "# Добавляем сумму в конец списка\n",
    "ivan_tsarevich.insert(0, \"ivan_tsarevich\")\n",
    "ivan_tsarevich.append(ivan_tsarevich_sum_11)\n",
    "ivan_tsarevich.append(ivan_tsarevich_sum_8)\n",
    "\n",
    "tsarevna_lyagushka = duble(body_4)\n",
    "tsarevna_lyagushka_sum_11 = sum(x for x in tsarevna_lyagushka if x == 12 or x == 4 or x == 8)\n",
    "tsarevna_lyagushka_sum_8 = sum(x for x in tsarevna_lyagushka if x == 8)\n",
    "# Добавляем сумму в конец списка\n",
    "tsarevna_lyagushka.insert(0, \"tsarevna_lyagushka\")\n",
    "tsarevna_lyagushka.append(tsarevna_lyagushka_sum_11)\n",
    "tsarevna_lyagushka.append(tsarevna_lyagushka_sum_8)\n",
    "\n",
    "# Форматируем вывод через точку с запятой\n",
    "def format_output(lst):\n",
    "    return ';'.join(map(str, lst))\n",
    "# Выводим результаты\n",
    "print(\"kashey_bessmertny:\", format_output(kashey_bessmertny))\n",
    "print(\"baba_yaga:\", format_output(baba_yaga))\n",
    "print(\"ivan_tsarevich:\", format_output(ivan_tsarevich))\n",
    "print(\"tsarevna_lyagushka:\", format_output(tsarevna_lyagushka))\n",
    "\n",
    "#чтение файла\n",
    "try:\n",
    "\n",
    "    with open(path_file, 'w', encoding='utf-8') as file_graphic:\n",
    "        file_graphic.write(f\"Воскресенья в {today.strftime('%B %Y')}: {sundays}\\n\")\n",
    "        file_graphic.write(f\"{format_output(kashey_bessmertny)}\\n\")\n",
    "        file_graphic.write(f\"{format_output(baba_yaga)}\\n\")\n",
    "        file_graphic.write(f\"{format_output(ivan_tsarevich)}\\n\")\n",
    "        file_graphic.write(f\"{format_output(tsarevna_lyagushka)}\\n\")\n",
    "\n",
    "    # Создаем список всех строк для Excel\n",
    "    all_data = [\n",
    "        [f\"Воскресенья в {today.strftime('%B %Y')}: {sundays}\"],\n",
    "        kashey_bessmertny,\n",
    "        baba_yaga,\n",
    "        ivan_tsarevich,\n",
    "        tsarevna_lyagushka\n",
    "    ]\n",
    "    \n",
    "    # Находим максимальную длину строки для определения количества столбцов\n",
    "    max_columns = max(len(row) if isinstance(row, list) else 1 for row in all_data)\n",
    "    \n",
    "    # Создаем список для DataFrame\n",
    "    excel_data = []\n",
    "    for row in all_data:\n",
    "        if isinstance(row, list):\n",
    "            # Добавляем строку и заполняем недостающие значения пустыми строками\n",
    "            excel_row = row + [''] * (max_columns - len(row))\n",
    "            excel_data.append(excel_row)\n",
    "        else:\n",
    "            excel_data.append([row] + [''] * (max_columns - 1))\n",
    "    \n",
    "    # Создаем DataFrame\n",
    "    column_names = [f'Колонка_{i+1}' for i in range(max_columns)]\n",
    "    df = pd.DataFrame(excel_data, columns=column_names)\n",
    "    \n",
    "    # Сохраняем в Excel\n",
    "    df.to_excel('GRAPHIK.xlsx', sheet_name='MyGRAPHIK', index=False)\n",
    "    print(\"Файл Excel успешно создан!\")\n",
    "\n",
    "except FileNotFoundError:\n",
    "    print(f\"Ошибка: файл {path_file} не найден\")\n",
    "except Exception as e:\n",
    "    print(f\"Произошла ошибка: {e}\")\n",
    "finally:\n",
    "    print(\"\\nРабота программы завершена\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
